language: node_js
node_js:
- '5.9.0'
env: NODE_DEBUG=logdna
sudo: false
branches:
  only:
  - master
cache:
  directories:
  - node_modules
install:
- npm install
- npm install -g mocha
script:
- gulp test

