version: 2
jobs:
  publish:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
workflows:
  version: 2
  update_package:
    jobs:
      - publish:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?/
            branches:
              ignore: /.*/
